<a href="https://colab.research.google.com/github/gurudattamanpreet/Practice/blob/main/Practice_Medical_Research.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [3]:
url1=pd.read_csv('https://raw.githubusercontent.com/gurudattamanpreet/datasets/refs/heads/main/Normal.csv')
url2=pd.read_csv('https://raw.githubusercontent.com/gurudattamanpreet/datasets/refs/heads/main/Type_H.csv')
url3=pd.read_csv('https://raw.githubusercontent.com/gurudattamanpreet/datasets/refs/heads/main/Type_S.csv')

In [11]:
print(url1.shape)
print(url2.shape)
print(url3.shape)

(100, 7)
(60, 7)
(150, 7)

In [16]:
if set(url1.columns)== set(url2.columns)== set(url3.columns):
  print('all columns are same')
else:
  print('kuch gadbad h')

all columns are same

In [17]:
df=pd.concat([url1,url2,url3])

In [18]:
df.head()

   P_incidence     P_tilt    L_angle    S_slope    P_radius  S_Degree   Class
0    38.505273  16.964297  35.112814  21.540976  127.632875  7.986683  Normal
1    54.920858  18.968430  51.601455  35.952428  125.846646  2.001642  Normal
2    44.362490   8.945435  46.902096  35.417055  129.220682  4.994195  Normal
3    48.318931  17.452121  48.000000  30.866809  128.980308 -0.910941  Normal
4    45.701789  10.659859  42.577846  35.041929  130.178314 -3.388910  Normal

In [19]:
df.shape

(310, 7)

In [20]:
df['Class'].value_counts()

Class
Type_S    133
Normal     73
Type_H     37
Nrmal      27
type_h     23
tp_s       17
Name: count, dtype: int64

In [21]:
df['Class']=df['Class'].replace('Normal','Nrmal')
df['Class']=df['Class'].replace('Type_S','tp_s')
df['Class']=df['Class']

Class
Type_S    133
Nrmal     100
Type_H     37
type_h     23
tp_s       17
Name: count, dtype: int64